title: Goa's Blog
email: goa.docs@gmail.com
description: My quest to achieve mindfullness and productivity
baseurl:
url:

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

incremental: true
permalink: /:categories/:title