title: Goa's Blog
email: goa.docs@gmail.com
description: In this blog you can find articles related with my passions, mainly computers.
url: "https://goamaral.github.io"
baseurl: ""
repository: goamaral/goamaral.github.io

markdown: kramdown
# incremental: true
permalink: /posts/:year/:month/:day/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag

postcss:
  cache: false

exclude:
  - bin/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
  - vendor/
