title: Goa's Blog
email: goa.docs@gmail.com
description: In this blog you can find articles related with my passions, mainly computers.
baseurl:
url:

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

incremental: true
permalink: /:categories/:title